name: brendamc
favicon: null
layout_spectrum: 0.26358
typography_spectrum: 0.2592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f87d2f'
    - '#c1c7ba'
    - '#346d20'
    - '#729346'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.8301306010689586
purpose: []
